### ISSUE TITLE
Class to <tr>

### ISSUE THREAD

**Issue by foscone** [jeremyHixon/RationalOptionPages#13]
Hi, is there a way to add class to `<tr>` element?
I added `'class' => 'my_custom_class'` under a single field array but it assign the class to the input element.
Thanks
Fosco

**Comment by jeremyHixon** [comment]
Try passing an 'args' parameter with the value of an array with the 'class' you want. Something like this:

```php
'field' => array(
	'title' => 'My Title',
	'args' => array(
		'class' => 'my_custom_class',
	),
),
```
It uses the `add_settings_field` function which accepts an `args` parameter which also accepts a `class` parameter that applies a class to the `tr` element according to the documentation:
https://developer.wordpress.org/reference/functions/add_settings_field/#parameters

**Comment by foscone** [comment]
It works!
Thank you very much!
