### ISSUE TITLE
Disabling media buttons on wp_editor

### ISSUE THREAD

**Issue by cstielper** [jeremyHixon/RationalOptionPages#15]
Is there a way to pass parameters to wp_editor in the $pages array, for instance, to remove media buttons? I tried a few different things, but haven't had much luck. I also tried changing line 94 to:

```php
'media_buttons' => false,
```

but the button is still there.

**Comment by jeremyHixon** [comment]
Apologies for the delay.

The code to instantiate the `wp_editor` starts on like `507`. Try adding your above code below the `textarea_name` parameter.

https://github.com/jeremyHixon/RationalOptionPages/blob/master/RationalOptionPages.php#L506
