### ISSUE TITLE
Settings saved notice is not getting displayed

### ISSUE THREAD

**Issue by gurumark** [jeremyHixon/RationalOptionPages#16]
Hi,
I am trying to reproduce your demo code in the readme. I put it in the functions.php as it is without any modifications. It created the page with all fields. It can also save and put the values in the database. But it does not show a "settings saved notice". What could be the reason? Am I missing anything?

Thanks.

**Comment by jeremyHixon** [comment]
You're looking for the `settings_errors()` function. Try putting it above the `do_settings_sections()` function in your options page callback.

**Comment by diogenesjup** [comment]
Same Here, and function settings_errors() and do_settings_sections() in callback do not solved

**Comment by jeremyHixon** [comment]
Fixed with 06c934d3d5b3bb32635fccf5e21fc4e09f9e4e72
