### ISSUE TITLE
Keep text format using wp_editor

### ISSUE THREAD

**Issue by foscone** [jeremyHixon/RationalOptionPages#17]
Hi, if I use `'type' => 'wp_editor'` it works correctly but when I save, it lose all text formats (bold, italic etc..) and the page reloads without keeping text format.
How can I solve it?
And then, when I use it, is it enough to echo it?
Thanks

**Comment by jeremyHixon** [comment]
Ah, yea, that's likely the unconventional method by which I appear to be sanitizing the input. It's on this [line 585](https://github.com/jeremyHixon/RationalOptionPages/blob/master/RationalOptionPages.php#L585).

WP Editor should be sanitized using something like [wp_kses_post()](https://developer.wordpress.org/reference/functions/wp_kses_post/).

You can add a case into that switch starting on [line 576](https://github.com/jeremyHixon/RationalOptionPages/blob/master/RationalOptionPages.php#L576) that will likely solve your problem. I also really need to fix that in the code.

```
switch ( $field['type'] ) {
	case 'checkbox':
		if ( empty( $input[ $field['id'] ] ) ) {
			$input[ $field['id'] ] = false;
		}
		break;
	case 'wp_editor':
		$input[ $field['id'] ] = wp_kses_posr( $input[ $field['id'] ] );
		break;
	default:
		// Sanitize by default; skip if this field's 'sanitize' setting is false.
		if ( !isset($field['sanitize'])  || $field['sanitize'] ) {
			$input[ $field['id'] ] = strip_tags($input[ $field['id'] ]);
			$input[ $field['id'] ] = esc_attr($input[ $field['id'] ]);								
		}
}
```

**Comment by foscone** [comment]
Ok, it works but when I save, it lose all text formats again (only in the wp_editor, in front-end the text has the right format).
I think the problem is in the "initial content" field of the wp_editor function.

**Comment by jeremyHixon** [comment]
Yea, I see what you mean. Modify line 387 with...
```
if ( ( !isset( $field['sanitize'] ) || $field['sanitize'] ) && $field['type'] !== 'wp_editor' ) {
```

**Comment by foscone** [comment]
Yes, now it works perfectly!
Thank you very much!

**Comment by jeremyHixon** [comment]
Thank you for point these out.
