### ISSUE TITLE
Load setting from other plugin

### ISSUE THREAD

**Issue by Webnemer** [jeremyHixon/RationalOptionPages#23]
Hi,

Is it possible to load a settings field from an other plugin.
I like to "copy" the Google Analytics Tracking ID from the Perfmatters plugin into a own options page.

**Comment by jeremyHixon** [comment]
Sorry, I totally missed this message.

It should be possible to do that. You would just have to find how it's
stored in the database and then retrieve it on your options page. That
being said, it wouldn't work just with the code provided. You'd have to
write some custom code to tell the options page where to get the data from.
