### ISSUE TITLE
Issue with setting page with appearance menu. 

### ISSUE THREAD

**Issue by alanjacobmathew** [jeremyHixon/RationalOptionPages#25]
Hi @jeremyHixon 

I am pretty new to wordpress plugins and this tool just amazes the way it can create menus.
I wanted to create a page that is right above 'Appearance Menu'. I was using the Page Generator tool and the result for 2 different setting are same. The settings are as following

**Setting1**
Menu Option: Position-> Separator (Below Comment) 

**Setting2**
Menu Option: Position-> Appearance

My question is isn't the **setting1** supposed to display the new menu above the appearance tab?

I compare the codes for both settings and the difference is shown the image below
[https://i.imgur.com/U3N1vR4.png](url)

**Comment by jeremyHixon** [comment]
Apologies, it took me a while to realize that this was referencing the online code generator and not actually this class. I've made changes to that generator to fix the problem.
