### ISSUE TITLE
How to make certain field "required"? (Noob Question)

### ISSUE THREAD

**Issue by hams-rmdhn** [jeremyHixon/RationalOptionPages#47]
Hi there! 

How to make certain field "required" so user can't submit before fill the required fields?

**Comment by jeremyHixon** [comment]
@koderama Sorry for the delay in responding. It's busy on this end. I'll try and follow up soon.

**Comment by hams-rmdhn** [comment]
[SOLVED]

I should add:

`attributes{
  'required' => true,
}`

**Comment by jeremyHixon** [comment]
Awesome. Glad you sorted it out. Seems like something I should have been able to remember but this makes clear to me how long it's been since I worked on this. Thanks for sharing!
