### ISSUE TITLE
Register as subpage to WordPress "Settings"

### ISSUE THREAD

**Issue by MarkCanada** [jeremyHixon/RationalOptionPages#7]
How do I add the options page underneath the WordPress "Settings" instead of in the main menu?

**Comment by jeremyHixon** [comment]
Through the 'parent_slug' parameter, outlined here:
https://github.com/jeremyHixon/RationalOptionPages#subpages

According to WordPress documentation you can use 'options-general.php'.
https://codex.wordpress.org/Administration_Menus#Using_add_submenu_page

**Comment by MarkCanada** [comment]
Ah great. Thank you. I didn't know I could add that parameter right into the "root" page.
