### ISSUE TITLE
HTML in TextArea

### ISSUE THREAD

**Issue by MarkCanada** [jeremyHixon/RationalOptionPages#8]
I am trying to have users enter some HTML in two textarea blocks and when saving the HTML is being stripped out. How can I keep it in there?
Also...I can't seem to figure out how to set the cols and rows for the textarea. Would you happen to have an example?

**Comment by jeremyHixon** [comment]
On line `386` and `387` of `RationalOptionPages.php` remove:
```
$field['value'] = strip_tags($field['value']);
$field['value'] = esc_attr($field['value']);
```

**Comment by MarkCanada** [comment]
Thank you.
I also found that I had to remove it from 580 and 581 as well to save the fields.
